### ISSUE TITLE
Tax and invoice

### ISSUE THREAD

**Issue by Manthan2611** [Posnic/POSNIC-1.03#4]
Hello,

When i am putting 14.5% tax in sales entry then after viewing it in view sales it showing me 15%.
And how to make invoice after making sales entry?

**Comment by arda971** [comment]
hi 
i think that you not allow not to have the invoice when creating a sale but you can have it  if you view the sale and then click on add it will print a duplicate but it is your sales Receipt invoice you will need to move the script to the rigth add button
